### ISSUE TITLE
Unnecessary 'new()'

### ISSUE THREAD

**Issue by arrudagates** [S0raWasTaken/Threadripper-bot#5]
You can completely remove this block of code as this behavior can be replicated with `Default::default()`
https://github.com/S0raWasTaken/Threadripper-bot/blob/master/src/data_structs.rs#L20-L29

**Comment by S0raWasTaken** [comment]
Yea, totally unnecessary, since I could simply `#[derive(Default)]` to replicate the false boolean statements as default

**Comment by S0raWasTaken** [comment]
Fixed in #6
